name: Auto Update Subscription

on:
  schedule:
    # Запуск каждые 6 часов (можно настроить чаще/реже)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Проверка репозитория
      uses: actions/checkout@v3

    - name: Настройка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Установка библиотек
      run: pip install requests

    - name: Запуск скрипта слияния
      run: python update_sub.py

    - name: Сохранение обновленного файла в GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add subscription.txt
        git commit -m "Автоматическое обновление подписки" || exit 0
        git push
